### PR TITLE
Add USD-TWD conversion funtionality (basic)

### PR DESCRIPTION
**Pull request by MorganELLiot**
I believe I figured out all the functionality as laid out in the issue. Less sure I got my branch updated all the way in GitHub - hope so.

### CODE REVIEW

**Comment by komali2** [comment]
oh i didn' trealize you already had a pr holy shit

**Comment by komali2** [comment]
Make sure to `git add .` . Looks like `Currency.vue` didn't make it into this commit. Or try `git add currency/Currency.vue` and then commit again!

**Review by komali2 — CHANGES_REQUESTED** [review]
Currency.vue didn't make it into the commit! Add another commit with that file in it, and push. This branch and pull request will be updated then.

**Comment by MorganELLiot** [comment]
Just re-ran the commit after doing a git add - thanks for the reminder! I think it all made it in there this time. Look ok?

**Review by komali2 — APPROVED** [review]
asdf yay good job

**Pull request merged**
